### ISSUE TITLE
Cannot find module '@babel/runtime/helpers/interopRequireDefault'

### ISSUE THREAD

**Issue by gabmontes** [just-paja/lerna-isolate#4]
Trying to run `npx lerna-isolate bundle app` to pack my app just results in that error.

**Comment by ReadyPlayerNaN** [comment]
Thanks for the report, @gabmontes. I've just recently seen this error as well. Will check it out soon.

**Comment by ReadyPlayerNaN** [comment]
I added @babel/runtime in d0f061de96734034506071e5ec24d5104bf69ebe and the error was gone. Please try if it helps, @gabmontes.
